---
metadata:
  version: "v1"
scenario:
  metadata:
    complexity: Low
    id: 45
    name: Init-Container Hang
    platform: kubernetes
  spec:
    environment:
      applications:
        otel_demo:
          enabled: true
      tools:
        category: sre
        selected:
          - kubernetes-topology-monitor
    faults:
      - custom:
          name: hang-init-container
          hang_init_container:
            workload:
              kind: Deployment
              name: email
              namespace: "{{ applications_helm_releases.otel_demo.namespace }}"
            restart_policy: force
