---
- name: Pause pipeline execution
  hosts:
    - environment
  tasks:
    - name: Pausing for atleast two minutes
      ansible.builtin.pause:
        seconds: "{{ (duration_in_minutes | default(2)) | int * 60 }}"
      tags:
        - pause
