---
version: 3
images:
  base_image:
    name: quay.io/centos/centos:stream10
dependencies:
  python_interpreter:
    package_system: python3.12
    python_path: /usr/bin/python3.12
  ansible_core:
    # Require minimum of 2.18 to get ansible-inventory --limit option
    package_pip: ansible-core>=2.18.0
  ansible_runner:
    package_pip: ansible-runner
  galaxy: |
    ---
    collections:
      - name: awx.awx
        version: "24.6.1"
      - name: azure.azcollection
        version: "3.9.0"
      - name: amazon.aws
        version: "10.1.2"
      - name: theforeman.foreman
        version: "5.7.0"
      - name: google.cloud
        version: "1.9.0"
      - name: openstack.cloud
        version: "2.5.0"
      - name: community.vmware
        version: "6.1.0"
      - name: ovirt.ovirt
        version: "3.2.1"
      - name: kubernetes.core
        version: "6.2.0"
      - name: ansible.posix
        version: "2.1.0"
      - name: ansible.windows
        version: "3.2.0"
      - name: redhatinsights.insights
        version: "1.3.0"
      - name: kubevirt.core
        version: "2.2.3"
      - name: ansible.utils
        version: "6.0.0"
      - name: community.general
        version: "12.0.0"
      - name: community.aws
        version: "10.0.0"
  system: |
    git-core [platform:rpm]
    lsof [platform:rpm]
    procps [platform:rpm]
    which [platform:rpm]
    python3.12-devel [platform:rpm]
    libcurl-devel [platform:rpm compile]
    libuuid-devel [platform:rpm compile]
    krb5-devel [platform:rpm compile]
    krb5-workstation [platform:rpm]
    subversion [platform:rpm]
    subversion [platform:dpkg]
    git-lfs [platform:rpm]
    sshpass [platform:rpm]
    rsync [platform:rpm]
    epel-release [platform:rpm]
    unzip [platform:rpm]
    podman-remote [platform:rpm]
    jq [platform:rpm]
    cmake [platform:rpm]
    gcc [platform:rpm]
    gcc-c++ [platform:rpm]
    make [platform:rpm]
    openssl-devel [platform:rpm compile]
    tcl-devel [platform:rpm]
    tk-devel [platform:rpm]
    make [platform:rpm]
  python: |
    ansible-sign @ git+https://github.com/ansible/ansible-sign@59d5c75ef202ed1c57e124a378e59d1d4045219b
    ncclient==0.7.0
    paramiko==4.0.0
    pykerberos==1.2.4
    pyOpenSSL==24.2.1
    pypsrp==0.8.1
    pywinrm==0.5.0
    toml==0.10.2
    pexpect==4.9.0
    python-daemon==3.1.2
    PyYAML==6.0.3
    six==1.16.0
    receptorctl==1.6.1
additional_build_steps:
  append_base:
    - RUN $PYCMD -m pip install -U pip
    # https://stackoverflow.com/questions/63994247/how-to-install-kubectl-and-helm-using-dockerfile
    # Multi-line seems to fail; hence
    - RUN ARCH=$(uname -m) && case "$ARCH" in x86_64) echo "export KUBECTL_ARCH=amd64" >> /etc/environment && echo "export HELM_ARCH=amd64" >> /etc/environment && echo "export AWS_ARCH=x86_64" >> /etc/environment;; aarch64) echo "export KUBECTL_ARCH=arm64" >> /etc/environment && echo "export HELM_ARCH=arm64" >> /etc/environment && echo "export AWS_ARCH=aarch64" >> /etc/environment;; esac
    - RUN . /etc/environment && curl -L "https://dl.k8s.io/release/v1.33.0/bin/linux/${KUBECTL_ARCH}/kubectl" -o kubectl && chmod +x ./kubectl && mv ./kubectl /usr/local/bin/kubectl
    - RUN . /etc/environment && curl -L "https://get.helm.sh/helm-v3.16.3-linux-${HELM_ARCH}.tar.gz" -o helm.tar.gz && tar -xvf helm.tar.gz && mv ./linux-${HELM_ARCH}/helm /usr/local/bin/helm
  append_final:
    - COPY --from=quay.io/ansible/receptor:devel /usr/bin/receptor /usr/bin/receptor
    - RUN mkdir -p /var/run/receptor
    - RUN git lfs install --system
    - RUN . /etc/environment && curl -L "https://awscli.amazonaws.com/awscli-exe-linux-${AWS_ARCH}.zip" -o awscli-exe.zip && unzip awscli-exe.zip && ./aws/install && rm awscli-exe.zip && rm -rf aws
