---
- name: Retrieve gateway from cluster
  kubernetes.core.k8s_info:
    api_version: gateway.networking.k8s.io
    kind: Gateway
    kubeconfig: "{{ faults_cluster.kubeconfig }}"
    name: "{{ spec.gateway.name }}"
    namespace: "{{ spec.gateway.namespace }}"
  register: faults_gateway

- name: Validate that gateway exists
  ansible.builtin.assert:
    that:
      - faults_gateway is defined
      - faults_gateway.resources | length == 1
    fail_msg: Unable to find gateway. Please verify that the gateway exists.
    success_msg: Found gateway.

- name: Inject fault (Authorization Policy Deny)
  kubernetes.core.k8s:
    kubeconfig: "{{ faults_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: security.istio.io/v1
      kind: AuthorizationPolicy
      metadata:
        name: "{{ faults_gateway.resources[0].metadata.name }}-deny"
        namespace: "{{ faults_gateway.resources[0].metadata.namespace }}"
      spec:
        action: DENY
        targetRef:
          group: gateway.networking.k8s.io
          kind: Gateway
          name: "{{ faults_gateway.resources[0].metadata.name }}"
        rules:
          - to:
              - operation:
                  methods: "{{ spec.methods }}"
    state: present
    wait: true
    wait_condition:
      reason: Accepted
      status: "True"
      type: WaypointAccepted
