---
- name: Import invalid password removal tasks
  ansible.builtin.import_tasks:
    file: remove_valkey_invalid_password.yaml
  vars:
    spec: "{{ fault.valkey.invalid_password }}"
  when:
    - fault.valkey.name == 'invalid-password'
    - fault.valkey.invalid_password is defined

- name: Import fill storage removal tasks
  ansible.builtin.import_tasks:
    file: remove_valkey_fill_storage.yaml
  vars:
    spec: "{{ fault.valkey.fill_storage }}"
  when:
    - fault.valkey.name == 'fill-storage'
    - fault.valkey.fill_storage is defined
