---
# This definition has been left purposely incomplete. This allows
# Dependabot to track the image. The full definition is provided in the
# template version of this object.

apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      containers:
        - image: registry.access.redhat.com/ubi10/python-312-minimal:10.1-1763382423
