---
tools_helm_releases:
  chaos_mesh:
    name: chaos-mesh
    namespace: chaos-mesh
  clickhouse:
    name: clickhouse
    namespace: clickhouse
  clickhouse_operator:
    name: clickhouse-operator
    namespace: clickhouse-operator
  ingress:
    name: ingress-nginx
    namespace: ingress-nginx
  istio:
    components:
      base: istio-base
      cni_node_agent: istio-cni
      istiod_control_plane: istiod
      ztunnel: ztunnel
    namespace: istio-system
  istio_gateway:
    name: istio-ingress
    namespace: istio-ingress
  kubernetes_metrics_server:
    name: metrics-server
    namespace: metrics-server
  kubernetes_topology_monitor:
    name: topology-monitor
    namespace: kube-system
  opencost:
    name: opencost
    namespace: opencost
  opensearch:
    name: opensearch
    namespace: opensearch
  opentelemetry_operator:
    name: opentelemetry-operator
    namespace: opentelemetry-operator
  prometheus:
    name: prometheus
    namespace: prometheus
