---
tools_helm_releases:
  chaos_mesh:
    name: chaos-mesh
    namespace: chaos-mesh
  clickhouse_operator:
    name: clickhouse-operator
    namespace: clickhouse-operator
  istio:
    components:
      base: istio-base
      cni_node_agent: istio-cni
      istiod_control_plane: istiod
      ztunnel: ztunnel
    namespace: istio-system
  kubernetes_metrics_server:
    name: metrics-server
    namespace: metrics-server
  kubernetes_topology_monitor:
    name: topology-monitor
    namespace: topology-monitor
  opencost:
    name: opencost
    namespace: opencost
  opensearch:
    name: opensearch
    namespace: opensearch
  opentelemetry_operator:
    name: opentelemetry-operator
    namespace: opentelemetry-operator
  prometheus:
    name: prometheus
    namespace: prometheus
