---
tools_instances:
  clickhouse:
    name: clickhouse
    namespace: clickhouse
  opentelemetry_collectors:
    names:
      istio: istio
      jaeger: jaeger
      kubernetes_events: kubenetes-events
    namespace: opentelemetry-collectors
