---
- name: Validate fault library index
  ansible.utils.validate:
    data: "{{ lookup('ansible.builtin.file', 'files/library/faults/index.json') | from_json }}"
    criteria: "{{ lookup('ansible.builtin.file', 'files/library/faults/schema.json') | from_json }}"
    engine: ansible.utils.jsonschema
