---
- name: Uninstall Chaos Mesh
  kubernetes.core.helm:
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    release_name: "{{ tools_helm_releases.chaos_mesh.name }}"
    release_namespace: "{{ tools_helm_releases.chaos_mesh.namespace }}"
    release_state: absent
    wait: true

- name: Delete the release namespace
  kubernetes.core.k8s:
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    resource_definition:
      api_version: v1
      kind: Namespace
      metadata:
        name: "{{ tools_helm_releases.chaos_mesh.namespace }}"
    state: absent
    wait: true

- name: Delete SCC for Chaos Mesh
  kubernetes.core.k8s:
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: security.openshift.io/v1
      kind: SecurityContextConstraints
      metadata:
        name: it-bench-chaos-daemon-restricted
    state: absent
    wait: true
  when:
    - tools_cluster.platform == "openshift"

- name: Append Chaos Mesh related CRDs to list
  ansible.builtin.set_fact:
    tools_custom_resource_definitions: "{{ tools_custom_resource_definitions + crds }}"
  vars:
    crds: "{{ tools_crds.resources | selectattr('spec.group', '==', 'chaos-mesh.org') }}"
