---
- name: Uninstall Nginx Ingress
  kubernetes.core.helm:
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    release_name: "{{ tools_helm_releases.ingress.name }}"
    release_namespace: "{{ tools_helm_releases.ingress.namespace }}"
    release_state: absent
    wait: true

- name: Delete the release namespace
  kubernetes.core.k8s:
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    resource_definition:
      api_version: v1
      kind: Namespace
      metadata:
        name: "{{ tools_helm_releases.ingress.namespace }}"
    state: absent
    wait: true
    wait_timeout: 180
