---
- name: Uninstall OpenTelemetry Collector for Kubernetes Events
  kubernetes.core.helm:
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    release_name: "{{ helm_releases.collectors.names.kubernetes_events }}"
    release_namespace: "{{ helm_releases.collectors.namespace }}"
    release_state: absent
    wait: true
  when:
    - tools_required.opentelemetry

- name: Retrieve all collector instances in the release namespace
  kubernetes.core.k8s_info:
    api_version: opentelemetry.io/v1beta1
    kind: OpenTelemetryCollector
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    namespace: "{{ helm_releases.collectors.namespace }}"
  register: opentelemetry_collector_info
  when:
    - tools_required.jaeger

- name: Delete all collector instances in the release namespace
  kubernetes.core.k8s:
    api_version: opentelemetry.io/v1beta1
    delete_all: true
    kind: OpenTelemetryCollector
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    namespace: "{{ helm_releases.collectors.namespace }}"
    state: absent
    wait: true
  when:
    - tools_required.jaeger
    - opentelemetry_collector_info.resources | length > 0

- name: Uninstall OpenTelemetry Operator
  kubernetes.core.helm:
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    release_name: "{{ helm_releases.operator.name }}"
    release_namespace: "{{ helm_releases.operator.namespace }}"
    release_state: absent
    wait: true
  when:
    - tools_required.jaeger
    - tools_cluster.platform == "kubernetes"

- name: Delete the subscription for RH build of OpenTelemetry Operator
  kubernetes.core.k8s:
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: opentelemetry-product
        namespace: openshift-opentelemetry-operator
    state: absent
  when:
    - tools_required.jaeger
    - tools_cluster.platform == "openshift"

- name: Delete the operator group for RH build of OpenTelemetry Operator
  kubernetes.core.k8s:
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: operators.coreos.com/v1
      kind: OperatorGroup
      metadata:
        name: openshift-opentelemetry-operator
        namespace: openshift-opentelemetry-operator
    state: absent
  when:
    - tools_required.jaeger
    - tools_cluster.platform == "openshift"

- name: Delete the project for RH build of OpenTelemetry Operator
  kubernetes.core.k8s:
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: project.openshift.io/v1
      kind: Project
      metadata:
        name: openshift-opentelemetry-operator
    state: absent
  when:
    - tools_required.jaeger
    - tools_cluster.platform == "openshift"

- name: Delete the release namespaces
  kubernetes.core.k8s:
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    resource_definition:
      api_version: v1
      kind: Namespace
      metadata:
        name: "{{ item }}"
    state: absent
    wait: true
  loop:
    - "{{ helm_releases.collectors.namespace }}"
    - "{{ helm_releases.operator.namespace }}"
