name: Perform build tests SRE tool images

on:
  pull_request:
    branches:
      - main
    paths:
      - sre/tools/**

jobs:
  topology-monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4.2.2
      - name: Login to Quay.io
        uses: docker/login-action@v3.4.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1
      - name: Build and push Kubernetes Topology Monitor
        uses: docker/build-push-action@v6.18.0
        env:
          DOCKER_BUILD_RECORD_UPLOAD: false
        with:
          context: sre/tools/kubernetes-topology-monitor
          platforms: |
            linux/amd64
            linux/arm64
          push: false
          tags: |
            quay.io/it-bench/topology-monitor:0.0.4
            quay.io/it-bench/topology-monitor:latest
  hello-bench:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture:
          - amd64
          - arm64
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4.2.2
      - name: Login to Quay.io
        uses: docker/login-action@v3.4.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1
      - name: Build and push Hello Bench image (amd)
        uses: docker/build-push-action@v6.18.0
        env:
          DOCKER_BUILD_RECORD_UPLOAD: false
        with:
          context: sre/tools/hello-bench
          platforms: |
            linux/${{ matrix.architecture }}
          push: false
          tags: |
            quay.io/it-bench/hello-bench-${{ matrix.architecture }}:1.0.0
            quay.io/it-bench/hello-bench-${{ matrix.architecture }}:latest
